### ISSUE TITLE
Error electron-prebuilt v2

### ISSUE THREAD

**Issue by DavidoffGithub** [mochman/MMM-Swipe#9]
Error:

```
> MMM-Swipe@1.1.1 postinstall /home/pi/MagicMirror/modules/MMM-Swipe
> electron-rebuild -e ../../node_modules/electron-prebuilt

An unhandled error occurred inside electron-rebuild
Unable to find electron-prebuilt's version number, either install it or specify an explicit version

Error: Unable to find electron-prebuilt's version number, either install it or specify an explicit version
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Swipe/node_modules/electron-rebuild/lib/src/cli.js:80:19)
    at Generator.next (<anonymous>)
    at /home/pi/MagicMirror/modules/MMM-Swipe/node_modules/electron-rebuild/lib/src/cli.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pi/MagicMirror/modules/MMM-Swipe/node_modules/electron-rebuild/lib/src/cli.js:4:12)
    at /home/pi/MagicMirror/modules/MMM-Swipe/node_modules/electron-rebuild/lib/src/cli.js:69:8
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Swipe/node_modules/electron-rebuild/lib/src/cli.js:145:4)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! MMM-Swipe@1.1.1 postinstall: `electron-rebuild -e ../../node_modules/electron-prebuilt`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the MMM-Swipe@1.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-02-27T23_04_06_839Z-debug.log
```

After changing the package.json File like already mentionend in another Issue Report (matthiasmwolf  on 6 Apr 2017 ) I am getting no more Errors....

```
pi@raspberrypi:~/MagicMirror/modules/MMM-Swipe $ npm install
> MMM-Swipe@1.1.1 postinstall /home/pi/MagicMirror/modules/MMM-Swipe
> electron-rebuild -e ../../node_modules/electron

✔ Rebuild Complete
up to date in 6.914s
```

 ...but I can't see the two different sensors in the calibration mode or getting any response in the verbose mode… So I guess the change from  electron-rebuild -e ../../node_modules/electron-prebuilt in package.json to electron-rebuild -e ../../node_modules/electron does not work for me.

Woulda be nice if someone could mention a solution or mby send me a working version of the MMM-Swipe. 

Thank you

**Comment by Jacob12138xieyuan** [comment]
same issue!

**Comment by Omaley** [comment]
I have the same issue; anyone made it work recently ?
